<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>My gallery</title>
    <style>
        body {
            width: 75vw;
            margin: 10px auto;
        }
        h1 {
            text-align: center;
        }
        .gallery {
            display: flex;
            justify-content: space-around;
            flex-flow: row nowrap;
        }
        .imgGallery {
            display: flex;
            justify-content: space-around;
            flex-flow: row wrap;
            flex: 0 0 70%;
        }
        .docGallery {
            display: flex;
            justify-content: flex-start;
            flex-direction: column;
            flex: 0 0 25%;
        }
        .image img {
            margin: 20px;
            max-width: 250px;
            max-height: 250px;
        }
    </style>
</head>
<body>
<h2><a href="upload-files.phtml">Add new files</a></h2>

<h1>Gallery</h1>
<div class="gallery">
    <div class="docGallery">
        <h3>Docs list</h3>
        <?php foreach ($docFiles as $file) : ?>
            <div class="docs"><p><?=$file ?></p></div>
        <?php endforeach; ?>
    </div>
    <div class="imgGallery">
        <?php foreach ($imgFiles as $file) : ?>
            <div class="image"><img src="<?= $imgDir . '/' . $file?>" alt="<?=$file ?>"></div>
        <?php endforeach; ?>
    </div>
</div>

</body>
</html>
